saasify-sh/saasify

packages/react-saasify/src/components/Logo/styles.module.css, packages/react-saasify/src/components/NavHeader/NavHeader.js, packages/react-saasify/src/components/PricingPlan/PricingPlan.js, packages/react-saasify/src/components/SignupForm/SignupForm.js, packages/react-saasify/src/themes/index.js, packages/react-saasify/src/themes/waves.js, packages/react-saasify/src/themes/waves.module.css
Introduces a new theme called **Waves**.
A few subtle core changes have been implemented.
Further core changes are required for below, which will be done in follow up PR.
=> Add waves theme

packages/react-saasify/src/components/CodeBlock/CodeBlock.js, packages/react-saasify/src/lib/theme.js, packages/react-saasify/src/themes/waves/index.js, packages/react-saasify/src/themes/waves/waves.module.css
Title says it all. Opted to just use vs2015 syntax highlighting for waves rather than spend too long rolling my own.
=> Theme level code themes, and waves code theme

examples/typescript/remove-bg/readme.md, lerna.json, packages/react-saasify/package.json, packages/saasify-cli/lib/auth.js, packages/saasify-cli/lib/cli.js, packages/saasify-cli/lib/commands/teams.js, packages/saasify-cli/package.json, packages/saasify-cli/readme.md, packages/saasify-client/index.js, packages/saasify-client/package.json, packages/saasify-codegen/package.json, packages/saasify-to-openapi/package.json, packages/saasify-utils/lib/username-blacklist.json, packages/saasify-utils/package.json
Could probably use more testing and docs, but the core functionality all seems to be working as intended.
=> WIP: Add support for teams

packages/react-saasify/src/components/NavHeader/NavHeader.js, packages/react-saasify/src/components/NavHeader/styles.module.css, packages/react-saasify/src/components/Section/styles.module.css, packages/react-saasify/src/themes/okta.module.css, packages/react-saasify/src/themes/waves/waves.module.css
PRing into #28 as branched off from there.
Didn't put icon in as antd wasn't playing ball, but feel free.
=> Add expanding Menu on mobile

packages/react-saasify/src/components/NavHeader/NavHeader.js, packages/react-saasify/src/components/NavHeader/styles.module.css, packages/react-saasify/src/components/Section/styles.module.css, packages/react-saasify/src/themes/okta.module.css, packages/react-saasify/src/themes/waves/index.js, packages/react-saasify/src/themes/waves/waves.module.css
See commit history for description
=> Polishes for sharp

packages/react-saasify/src/themes/waves/index.js, packages/react-saasify/src/themes/waves/waves.module.css
=> feat: add codeBlockDark param to waves

examples/typescript/imagemin/readme.md, examples/typescript/natural/readme.md, examples/typescript/sharp/readme.md
Following feedback from OSS authors, I've sought to clarify the wording around revenue in our example projects.
=> Clarify revenue messaging in examples

packages/react-saasify/src/themes/waves/waves.module.css
Related to https://github.com/transitive-bullshit/saasify/pull/17
=> Improve waves onboarding and fix checkout

examples/python/wordcloud/saasify.json, packages/react-saasify/src/themes/waves/waves.module.css
=> (WIP) Polish wordcloud

examples/python/wordcloud/readme.md
Makes readme play better with #46
=> docs: update wordcloud README headings so they index in redoc

docs/showcase.md, packages/react-saasify/package.json, packages/react-saasify/src/components/ServiceForm/ServiceForm.js, packages/react-saasify/src/components/ServiceForm/ServiceInputJSON.js, packages/react-saasify/src/components/ServiceForm/styles.module.css, packages/react-saasify/src/lib/react-simple-code-editor.js, packages/react-saasify/src/lib/react-syntax-highlighter.js, packages/react-saasify/src/themes/waves/waves.module.css, packages/react-saasify/yarn.lock
=> JSON playground inputs

packages/saasify-cli/lib/cli.js, packages/saasify-cli/package.json
Command suggestion becomes a handy feature when the user makes a typo.
=> feat(cli): suggest matching commands

docs/cli.md
#53 fixed the usage information. Hence, updated the docs accordingly.
=> docs(cli): update usage info

package.json
`pre-commit` hook comes in handy in the Dev workflow.
=> feat(chore): configure pre-commit hook

packages/react-saasify/src/components/LoginForm/LoginForm.js, packages/react-saasify/src/components/SignupForm/SignupForm.js, packages/react-saasify/src/store/AuthManager.js, packages/saasify-client/index.js
This PR enables us to pass additional context data to the backend during auth API calls.
=> feat: Add support for auth context

packages/saasify-cli/lib/cli.js, packages/saasify-cli/lib/parse-config.js, packages/saasify-cli/package.json, packages/saasify-cli/yarn.lock
=> Add yaml config support

packages/saasify-cli/lib/cli.js, packages/saasify-cli/package.json
=> feat(chore): notify users of an available update

package.json
- Added `lint` script
- Configured `lint-staged` to autofix `lint` issues and stage the respective files.
=> chore: minor tweaks to lint-staged config

packages/react-saasify/src/components/UndrawSVG/UndrawSVG.js, packages/saasify-bulk-deploy/lib/get-projects.js, packages/saasify-cli/lib/auth-github.js, packages/saasify-utils/lib/parse-openapi.js
Switch over to `includes()` that checks for the existence of an item.
=> chore: minor code refactoring

readme.md
- Added reference to the `contributing guidelines`
- Made the `License` section lead to the respective file.
> It seems the `contributing guidelines` is to be worked on further to make it serve the purpose.
=> [Docs]: Minor enhancements

packages/react-saasify/src/components/LiveServiceDemo/styles.module.css, packages/react-saasify/src/components/NavHeader/NavHeader.js, packages/react-saasify/src/components/NavHeader/styles.module.css, packages/react-saasify/src/components/Section/styles.module.css, packages/react-saasify/src/themes/okta.module.css, packages/react-saasify/src/themes/waves/waves.module.css
Fix header, first section and live service demo in both okta and waves, also tweaking some font sizes.
=> Fix landing pages on mobile

packages/saasify-cli/readme.md
A little de-emphasis on OSS and more focus on APIs.  
This is just a suggestion, feel free to tweak the wording.
=> Update language to be consistent with pivot

docs/quick-start.md
Fixed 404 error on quick start page
=> fix: broken link
